### ISSUE TITLE
Regression in 0.4.1

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate-auto-replace#12]
Hi @wells @ianstormtaylor, on upgrading to 0.4.1 from 0.4.0, my code broke. Here are the relevant details when trying to detect a link in a sentence.

I am getting the following error:
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at eval (webpack:///./~/slate-auto-replace/dist/index.js?:181:37)
    at Array.forEach (native)
```

The relevant line of source code is [here](https://github.com/ianstormtaylor/slate-auto-replace/blame/master/lib/index.js#L166)

And I also printed out some helpful things for debugging.

**Console output**
```yaml
match: 
google.com

before: 
["google.com", "google.com", undefined, undefined, undefined, undefined, index: 5, input: "hello google.com"]

before.slice(1, before.length):
 ["google.com", undefined, undefined, undefined, undefined]
```

**Snippet**
```js
/*
*	Links. Detects a link in a sentence.
*	- http/https links, followed by a space, period or )
*	- www links followed by a space
*	- .tld links followed by a space
*/

const URL_AND_SPACE_AFTER = /(?:^|[^\(\/@])\b((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/?)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\)){0,}(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s\!()\[\]{};:\'\"\.\,<>?«»“”‘’]){0,})\s*/i;

AutoReplace({
	trigger:	triggerAutoDetection,
	before:		URL_AND_SPACE_AFTER,
	transform:	(transform, evt, data, matches, editor) => {
		const [input, match, text] = matches.before;

		const href = getLink(input);
		const anchorText = getAnchorText(input);

		const inlineLink = {
			type:	constants.INLINE_LINK,
			isVoid:	false,
			data: {
				href:	href
			}
		};

		return inlineLinkWithText(editor, transform, data, anchorText, inlineLink);
	}
}),
```

**Comment by ianstormtaylor** [comment]
Hey @wells can you check this out? I think it's from the PR. Thanks!

**Comment by wells** [comment]
The root issue is somewhere within the regular expression you are attempting to use. Notice that the before array of matches has undefined values at before[2] through before[5]? This means that your regular expression has created a series of undefined capture groups. 

The revision in 0.4.1 is designed to remove any characters found in resulting matching capture groups for a regex. 

Nevertheless, I have just submitted a pull request to ignore undefined capture group matches. @ianstormtaylor See pull request #13

**Comment by wells** [comment]
@oyeanuj the following updated regex changes the undefined capture groups found in your regex to non-capturing groups.

```
/(?:^|\s)((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/?)(?:[^\s()<>]+|\((?:[^\s()<>]+|(?:\([^\s()<>]+\)))*\)){0,}(?:\((?:[^\s()<>]+|(?:\([^\s()<>]+\)))*\)|[^\s\!()\[\]{};:\'\"\.\,<>?«»“”‘’]))/i
```

**Comment by ianstormtaylor** [comment]
Thank you @wells for the detailed explanation, I really appreciate it!

**Comment by oyeanuj** [comment]
@wells, thanks for that explanation. Regex isn't my strong point, so this is good to know!
