### ISSUE TITLE
Auto replace not working on paste

### ISSUE THREAD

**Issue by ouchxp** [ianstormtaylor/slate-auto-replace#15]
When pasting `(c)` directly in the example it does't do replacing at all.

**Comment by ianstormtaylor** [comment]
Hey @ouchxp good call, but this is out of the scope of this plugin. This one is purely focused on when a user types out the specific shortcuts.

**Comment by ouchxp** [comment]
Thanks for the quick response, that's a reasonable design choice.
I like slate very much, thanks for your amazing work.
