### ISSUE TITLE
insertInline loses focus in the editor

### ISSUE THREAD

**Issue by emlama** [ianstormtaylor/slate-auto-replace#17]
I can't tell if this is a bug or if I'm not doing this right. I couldn't find any examples of inserting an inline node but I have managed to get this working.

My schema looks like this:

````javascript
schema = {
  nodes: {
    t: (props) => {
      const { data } = props.node
      const label = data.get('label')
      return <span {...props.attributes} className="token" style={tokenStyle}>{label}</span>
    }
  }
}
````

And I'm calling the AutoReplace plugin like this:

````javascript
plugins = [
  AutoReplace({
    trigger: '}',
    before: /({{)(\w+)(})/,
    transform: (transform, e, data, matches, editor) => {
      return transform.insertInline({
        type: 't',
        isVoid: true,
        data: { label: matches.before[2] }
      })
    }
  })
];
````

What happens is a new inline node is inserted with the text but the editor no longer has a cursor placed in it so I can't keep typing.

Is there a more appropriate way to insert an inline node or possibly a way for me to set the cursor after this runs?

THanks!

**Comment by ianstormtaylor** [comment]
Hey @msaforrian I think this is probably a bug in the core Slate transform logic for handling selections with inline nodes. You might search through the Slate issues and see if one matches, or if not, please open an issue there with a JSFiddle reproduction and hopefully the root cause can be fixed! Thanks for taking the time to report this!

**Comment by emlama** [comment]
Hi @ianstormtaylor I was able to fix the issue by applying a .collapseToEndOfNextText() method to the transform.

What are your thoughts on a pull request that demonstrates how to add an inline node in the examples section? I had a hard time finding any documentation across this project and the Slate.js docs on how to insert Inline nodes and think others might run into similar problems.

**Comment by ianstormtaylor** [comment]
Hey @msaforrian I'm open to a pull request! The only thing I ask is that it not complicate things further by adding a new example ideally, or finds a solution that is similarly debt-reducing. I think the emoji example uses inline nodes already but I can't quite remember.

**Comment by emlama** [comment]
The emoji example does use inline nodes. How about having the trigger/before regex add up to a smiley face ":)" and it inserts a smiley emoji?

**Comment by ianstormtaylor** [comment]
@msaforrian sure that sounds like a great addition!
