### ISSUE TITLE
transform.setMark not possible

### ISSUE THREAD

**Issue by FrediBach** [ianstormtaylor/slate-auto-replace#18]
Maybe I'm missing something, but adding marks seems to not be possible?

Something like:

`AutoReplace({
    trigger: '*',
    before: /(\*)/,
    transform: (transform, e, data, matches) => {
      return transform.setMark({ type: 'bold' })
    }
  })`

Would be cool if this would be possible, so that both blocks and marks can be used.

**Comment by FrediBach** [comment]
Ah, my bad, It's setInline or addMark.

**Comment by ianstormtaylor** [comment]
@FrediBach glad you got it sorted!
