### ISSUE TITLE
Smart quotes

### ISSUE THREAD

**Issue by davidgeilfus** [ianstormtaylor/slate-auto-replace#3]
Hi @ianstormtaylor,

I was wondering if this plugin is intended to replace [slate-auto-replace-text](https://github.com/ianstormtaylor/slate-auto-replace-text) (and [slate-auto-replace-block](https://github.com/ianstormtaylor/slate-auto-replace-block))? If so, I can’t get my head around adapting the smart quotes example to this newer version… Especially the ` replacement: char => '“${char}'` part, would you have any tip?

Many thanks in advance! Best,

D.

**Comment by ianstormtaylor** [comment]
Hey @davidgeilfus good question. It's meant to replace `slate-auto-replace-block` yup, and then I was thinking of refactoring `slate-auto-replace-text` to use this new one under the hood, but just be a much simpler API for single-character replacements.

As for quotes, here's what I've got going in my editor right now:

```js
    /**
     * Quotes.
     */

    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: '\'',
      before: /[a-zA-Z]$/,
      transform: t => t.insertText('’')
    }),

    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: '"',
      before: /[a-zA-Z]$/,
      transform: t => t.insertText('”')
    }),

    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: /^[a-zA-Z]$/,
      before: /[a-zA-Z0-9](')$/,
      transform: (t, e) => t.insertText('’' + e.data)
    }),

    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: /^[a-zA-Z0-9]$/,
      before: /(?:^|[^a-zA-Z0-9])(')$/,
      transform: (t, e) => t.insertText('‘' + e.data)
    }),

    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: /^[a-zA-Z0-9]$/,
      before: /(?:^|[^a-zA-Z0-9])(")$/,
      transform: (t, e) => t.insertText('“' + e.data)
    }),
```

I hope that helps!

**Comment by davidgeilfus** [comment]
Many thanks @ianstormtaylor, it does help a lot!
