### ISSUE TITLE
Marks

### ISSUE THREAD

**Issue by davidgeilfus** [ianstormtaylor/slate-auto-replace#4]
Hi @ianstormtaylor,

I'm trying to set up this plugin to replace the following Markdown patterns with their corresponding marks: 

- `**text**` → `<strong>text</strong>`
- `*text*`→ `<em>text</em>`

I came up with this, which works fine for italics but also matches bolds:

    AutoReplace({
      trigger: '*',
      before: /(\*{1}(.+?))$/,
      transform: (transform, e, data, matches) => {
        var match = [...matches.before].pop();

        transform
          .addMark('italic')
          .insertText(match)
          .removeMark('italic');
      }
    })

Would you have any idea of regular expressions I could use to match one or the other? Also I'm not sure this is the best way to “wrap” text with a mark?

Many thanks for the help!

**Comment by ianstormtaylor** [comment]
Good question, I think there's probably a way to get fancy with regex's to make a single plugin instance handle both bold and italic, but the way I do it is to just add the bold plugin before the italic plugin in the stack. That way it will always try to match `**` first, and then `*`.

I think that is indeed the best way to wrap text with a mark, and it actually caused me to realize that my implementation using just `insertText(text, marks)` wouldn't preserve the existing marks on the text, so thank you!

**Comment by ianstormtaylor** [comment]
For context, here's part of the bold-matching code:

```js
    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: '*',
      before: /(\*\*([^\*]+)\*)$/,
      transform: (transform, e, data, matches) => {
        const [ input, match, text ] = matches.before
        return transform
          .addMark(BOLD_MARK)
          .insertText(text)
          .removeMark(BOLD_MARK)
      }
    }),

    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: '*',
      after: /^(\*([^\*]+)\*\*)/,
      transform: (transform, e, data, matches) => {
        const [ input, match, text ] = matches.after
        return transform
          .addMark(BOLD_MARK)
          .insertText(text)
          .removeMark(BOLD_MARK)
          .moveBackward(text.length)
      }
    }),
```

**Comment by davidgeilfus** [comment]
Thank you @ianstormtaylor! Here's what I've got in my editor:

```javascript
AutoReplace({
  ignoreIn: CODE_BLOCK,
  trigger: '*',
  before: /(\*\*([^\*]+)\*)$/,
  transform: (transform, e, data, matches) => {
    const [ input, match, text ] = matches.before;

    return transform
      .addMark(STRONG_MARK)
      .insertText(text)
      .removeMark(STRONG_MARK);
  }
}),
AutoReplace({
  ignoreIn: CODE_BLOCK,
  trigger: '*',
  before: /(\*([^\*]+))$/,
  transform: (transform, e, data, matches) => {
    const [ input, match, text ] = matches.before;

    return transform
      .addMark(EMPHASIS_MARK)
      .insertText(text)
      .removeMark(EMPHASIS_MARK);
  }
})
```

But when I try to wrap some text with two asterisks, here's what happens:

1. `**Text`
2. `**Text*` → `*_Text_` (the first following asterisk makes the text italic)
3. `*_Text_*` → `_Text_` (the second following asterisk makes the preceding asterisk disappear)

So it looks like, even if the bold plugin is defined before the italic plugin, the second matches the first… Any idea why?

Many thanks for the help!

**Comment by ianstormtaylor** [comment]
Ah you're totally right, I didn't read my italics code properly before responding 😄  here it is in full:

```js
    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: '*',
      before: /(?:^|[^\*])(\*([^\*]+))$/,
      transform: (transform, e, data, matches) => {
        const [ input, match, text ] = matches.before
        const mark = Mark.create({ type: ITALIC_MARK })
        const marks = Mark.createSet([mark])
        return transform
          .insertText(text, marks)
          .removeMark(ITALIC_MARK)
      }
    }),

    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: '*',
      after: /^(([^\*]+)\*)(?:^|[^\*])/,
      transform: (transform, e, data, matches) => {
        const [ input, match, text ] = matches.after
        const mark = Mark.create({ type: ITALIC_MARK })
        const marks = Mark.createSet([mark])
        return transform
          .insertText(text, marks)
          .moveBackward(text.length)
      }
    }),

    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: '_',
      before: /(?:^|[^_])(_([^_]+))$/,
      transform: (transform, e, data, matches) => {
        const [ input, match, text ] = matches.before
        const mark = Mark.create({ type: ITALIC_MARK })
        const marks = Mark.createSet([mark])
        return transform
          .insertText(text, marks)
          .removeMark(ITALIC_MARK)
      }
    }),

    AutoReplace({
      ignoreIn: CODE_BLOCK,
      trigger: '_',
      after: /^(([^_]+)_)(?:^|[^_])/,
      transform: (transform, e, data, matches) => {
        const [ input, match, text ] = matches.after
        const mark = Mark.create({ type: ITALIC_MARK })
        const marks = Mark.createSet([mark])
        return transform
          .insertText(text, marks)
          .moveBackward(text.length)
      }
    }),
```

It's actually using the regex approach to ensure that the character prior isn't a double `**`.

**Comment by davidgeilfus** [comment]
Wow, thank you so much! I've been struggling with these regular expressions for quite some time and they seem perfectly clear to me now…
