### ISSUE TITLE
Access to `editor` object during transform

### ISSUE THREAD

**Issue by thesunny** [ianstormtaylor/slate-auto-replace#6]
@ianstormtaylor 

Would you consider adding the `editor` to the transform callback?

One of the things that I have auto replace do is replace a URL on a link with a "Link Block".

It differs from a link in that it actually requests the web page (on the server) and grabs the `title` and a `description` of the page and adds it to the block.

The AutoReplace works in two phases:

1. It sets the {url: '...'} on the Block.
2. It makes a request to the server to go and find the title and description for the link. When it gets that information, it updates the Block with the new data {url: '...', title: '...', description: '...'}. I can't update the editor, however, because the transform doesn't have the editor data in it.

I can put in a PR if acceptable.

**Comment by ianstormtaylor** [comment]
Hey @thesunny, that sounds like a great use case, I'd definitely accept that PR. Thanks!
