### ISSUE TITLE
Array input to AutoReplace

### ISSUE THREAD

**Issue by oyeanuj** [ianstormtaylor/slate-auto-replace#9]
Hi @ianstormtaylor! Thank you for putting out this plugin! 

In your examples in some of the issues, and in my code as well, we end up having a long list of calls to the `AutoReplacePlugin`. I was wondering if an array of inputs to the plugin would be a feasible option for maybe a cleaner API? 

I imagine the export of the plugin then would be a single `onKeyDown` function as opposed to a multiple ones. That would allow one to have a pattern of multiple `AutoReplace` calls as part of a single plugin for Markdown or Typography, etc.

Thoughts?

**Comment by ianstormtaylor** [comment]
I think I'd like to avoid this for now, unless it ever becomes a performance problem, since it keeps everything simpler if multiple instances of plugins are always used to do multiple things. That way not every plugin has to implement array-or-object functionality.
